# Generated by Django 3.1.2 on 2020-10-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contest',
            fields=[
                ('site', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
        ),
    ]
