# Generated by Django 3.1.2 on 2020-11-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcontest', '0002_auto_20201031_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
