# Generated by Django 3.1.2 on 2020-10-31 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_active', models.BooleanField(default=False)),
                ('user2_active', models.BooleanField(default=False)),
                ('genration_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('winner', models.CharField(default='TO BE DECLARED', max_length=255)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codefight.problem')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkone', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linktwo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
